import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar 
        links = {[
          {link: '/', name: 'Home', key: 0},
          {link: '/explore', name: 'Explore', key: 1},
        ]}
      />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
